"""Renomear ativo para ativa em categorias

Revision ID: 72c2c8c8fded
Revises: d9b7d5c83e08
Create Date: 2026-08-21 15:56:30.839341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c2c8c8fded'
down_revision: Union[str, Sequence[str], None] = 'd9b7d5c83e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentacoes_id'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    op.add_column('categorias', sa.Column('ativa', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_column('categorias', 'ativo')
    op.alter_column('usuarios', 'senha_hash',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'senha_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=225),
               existing_nullable=True)
    op.add_column('categorias', sa.Column('ativo', sa.BOOLEAN(), nullable=True))
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.drop_column('categorias', 'ativa')
    op.create_table('movimentacoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=7), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('preco_unitario', sa.FLOAT(), nullable=False),
    sa.Column('observacao', sa.VARCHAR(length=255), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('produto_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_id'), 'movimentacoes', ['id'], unique=False)
    # ### end Alembic commands ###
